
package Interfaz;

import Paneles.*;
import java.awt.*;
import java.text.SimpleDateFormat;
import java.util.*;
import javax.swing.*;

public class Control extends javax.swing.JFrame {

    Calendar Ca;
    java.util.Date Actual;
    String fecha;
    int oficina=0, registrar=0, busqueda=0, informes=0, registros=0, opciones=0, salir=0; 
    
    public Control() {
        initComponents();
        //this.setExtendedState(6);
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(new java.awt.Color(153,153,153));
        Fecha();
        btn_oficinaMouseClicked(null);
    }
    
         
     //lbl_oficina.setFont(new Font("Cleanvertising-Light", Font.PLAIN, 22));
     //.setBackground(new java.awt.Color(232,2,14)); //Color rojo
    
    public void MauseExit(){
        btn_oficinaMouseExited(null);
        btn_registrarMouseExited(null);
        btn_busquedaMouseExited(null);
        btn_informesMouseExited(null);
        btn_registrosMouseExited(null);
        btn_opcionesMouseExited(null);
        btn_salirMouseExited(null);
    }
    
    public void Fecha(){
       SimpleDateFormat Sf = new SimpleDateFormat("dd 'de' MMMM 'de' yyyy", new Locale("ES"));
       SimpleDateFormat D = new SimpleDateFormat("d/MM/yyyy", new Locale("ES"));
       Ca=Calendar.getInstance();
       Actual =Ca.getTime();
       int d=Actual.getDay();
       String dia="";
       switch(d)
       {
           case 0: dia="domingo"; break;
           case 1: dia="lunes"; break;
           case 2: dia="martes"; break;
           case 3: dia="miercoles"; break;
           case 4: dia="jueves"; break;
           case 5: dia="viernes"; break; 
           case 6: dia="sabado"; break;     
       }
       lblFechaLarga.setText("Hoy es "+dia+", "+Sf.format(Actual));
       fecha=D.format(Actual);
    }
    
    public void Mostrar(JPanel Panel){
        Layer.removeAll();
        Panel.setSize(Layer.getSize());
        Layer.add(Panel, BorderLayout.CENTER);
    }
    public void Cerrar(){
        this.dispose();
    }
   
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_oficina = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lbl_oficina = new javax.swing.JLabel();
        btn_registrar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lbl_registrar = new javax.swing.JLabel();
        btn_busqueda = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lbl_busqueda = new javax.swing.JLabel();
        btn_informes = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        lbl_informes = new javax.swing.JLabel();
        btn_opciones = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        lbl_opciones = new javax.swing.JLabel();
        btn_registros = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        lbl_registros = new javax.swing.JLabel();
        btn_salir = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        lbl_salir = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblFechaLarga = new javax.swing.JLabel();
        Layer = new javax.swing.JLayeredPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(38, 38, 38));
        jPanel1.setPreferredSize(new java.awt.Dimension(1024, 120));

        btn_oficina.setBackground(new java.awt.Color(51, 51, 51));
        btn_oficina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_oficinaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_oficinaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_oficinaMouseExited(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Oficina_i.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_oficinaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_oficinaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_oficinaMouseExited(evt);
            }
        });

        lbl_oficina.setFont(new java.awt.Font("Cleanvertising ", 0, 22)); // NOI18N
        lbl_oficina.setForeground(new java.awt.Color(255, 255, 255));
        lbl_oficina.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_oficina.setText("CONTROL");
        lbl_oficina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_oficinaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_oficinaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_oficinaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btn_oficinaLayout = new javax.swing.GroupLayout(btn_oficina);
        btn_oficina.setLayout(btn_oficinaLayout);
        btn_oficinaLayout.setHorizontalGroup(
            btn_oficinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_oficina, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_oficinaLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(21, 21, 21))
        );
        btn_oficinaLayout.setVerticalGroup(
            btn_oficinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_oficinaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_oficina))
        );

        btn_registrar.setBackground(new java.awt.Color(51, 51, 51));
        btn_registrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_registrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_registrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_registrarMouseExited(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Registrar_i.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_registrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_registrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_registrarMouseExited(evt);
            }
        });

        lbl_registrar.setFont(new java.awt.Font("Cleanvertising ", 0, 22));
        lbl_registrar.setForeground(new java.awt.Color(255, 255, 255));
        lbl_registrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_registrar.setText("REGISTRO");
        lbl_registrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_registrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_registrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_registrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btn_registrarLayout = new javax.swing.GroupLayout(btn_registrar);
        btn_registrar.setLayout(btn_registrarLayout);
        btn_registrarLayout.setHorizontalGroup(
            btn_registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_registrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
            .addGroup(btn_registrarLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel3)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        btn_registrarLayout.setVerticalGroup(
            btn_registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_registrarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_registrar))
        );

        btn_busqueda.setBackground(new java.awt.Color(51, 51, 51));
        btn_busqueda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_busquedaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_busquedaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_busquedaMouseExited(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Busqueda_i.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_busquedaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_busquedaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_busquedaMouseExited(evt);
            }
        });

        lbl_busqueda.setFont(new java.awt.Font("Cleanvertising ", 0, 22));
        lbl_busqueda.setForeground(new java.awt.Color(255, 255, 255));
        lbl_busqueda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_busqueda.setText("CONSULTA");
        lbl_busqueda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_busquedaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btn_busquedaLayout = new javax.swing.GroupLayout(btn_busqueda);
        btn_busqueda.setLayout(btn_busquedaLayout);
        btn_busquedaLayout.setHorizontalGroup(
            btn_busquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_busqueda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
            .addGroup(btn_busquedaLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel5)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        btn_busquedaLayout.setVerticalGroup(
            btn_busquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_busquedaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_busqueda))
        );

        btn_informes.setBackground(new java.awt.Color(51, 51, 51));
        btn_informes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_informesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_informesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_informesMouseExited(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Informes_i.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_informesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_informesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_informesMouseExited(evt);
            }
        });

        lbl_informes.setFont(new java.awt.Font("Cleanvertising ", 0, 22));
        lbl_informes.setForeground(new java.awt.Color(255, 255, 255));
        lbl_informes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_informes.setText("INFORMES");
        lbl_informes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_informesMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btn_informesLayout = new javax.swing.GroupLayout(btn_informes);
        btn_informes.setLayout(btn_informesLayout);
        btn_informesLayout.setHorizontalGroup(
            btn_informesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_informes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
            .addGroup(btn_informesLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel7)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        btn_informesLayout.setVerticalGroup(
            btn_informesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_informesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_informes))
        );

        btn_opciones.setBackground(new java.awt.Color(51, 51, 51));
        btn_opciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_opcionesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_opcionesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_opcionesMouseExited(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Opciones_i.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_opcionesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_opcionesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_opcionesMouseExited(evt);
            }
        });

        lbl_opciones.setFont(new java.awt.Font("Cleanvertising ", 0, 22));
        lbl_opciones.setForeground(new java.awt.Color(255, 255, 255));
        lbl_opciones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_opciones.setText("OPCIONES");
        lbl_opciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_opcionesMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btn_opcionesLayout = new javax.swing.GroupLayout(btn_opciones);
        btn_opciones.setLayout(btn_opcionesLayout);
        btn_opcionesLayout.setHorizontalGroup(
            btn_opcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_opciones, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
            .addGroup(btn_opcionesLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel9)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        btn_opcionesLayout.setVerticalGroup(
            btn_opcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_opcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_opciones))
        );

        btn_registros.setBackground(new java.awt.Color(51, 51, 51));
        btn_registros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_registrosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_registrosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_registrosMouseExited(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Registros_i.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_registrosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_registrosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_registrosMouseExited(evt);
            }
        });

        lbl_registros.setFont(new java.awt.Font("Cleanvertising ", 0, 22));
        lbl_registros.setForeground(new java.awt.Color(255, 255, 255));
        lbl_registros.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_registros.setText("HISTORIAL");
        lbl_registros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_registrosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btn_registrosLayout = new javax.swing.GroupLayout(btn_registros);
        btn_registros.setLayout(btn_registrosLayout);
        btn_registrosLayout.setHorizontalGroup(
            btn_registrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_registros, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
            .addGroup(btn_registrosLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel11)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        btn_registrosLayout.setVerticalGroup(
            btn_registrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_registrosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_registros))
        );

        btn_salir.setBackground(new java.awt.Color(51, 51, 51));
        btn_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_salirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_salirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_salirMouseExited(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Salir_i.png"))); // NOI18N
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_salirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_salirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_salirMouseExited(evt);
            }
        });

        lbl_salir.setFont(new java.awt.Font("Cleanvertising ", 0, 22));
        lbl_salir.setForeground(new java.awt.Color(255, 255, 255));
        lbl_salir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_salir.setText("CERRAR");
        lbl_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_salirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btn_salirLayout = new javax.swing.GroupLayout(btn_salir);
        btn_salir.setLayout(btn_salirLayout);
        btn_salirLayout.setHorizontalGroup(
            btn_salirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_salir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_salirLayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(33, 33, 33))
        );
        btn_salirLayout.setVerticalGroup(
            btn_salirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_salirLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_salir))
        );

        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText(" - - - - - - - - -- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addComponent(btn_oficina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_registrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_informes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_registros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_opciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 1063, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_opciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_registros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_salir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_oficina, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_registrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_busqueda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_informes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jPanel9.setBackground(new java.awt.Color(38, 38, 38));

        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText(" - - - - - - - - -- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - ");

        lblFechaLarga.setFont(new java.awt.Font("Cleanvertising ", 0, 24));
        lblFechaLarga.setForeground(new java.awt.Color(204, 204, 204));
        lblFechaLarga.setText("Hoy es...");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 1063, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(lblFechaLarga, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(499, 499, 499))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(lblFechaLarga)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Layer, javax.swing.GroupLayout.DEFAULT_SIZE, 1043, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1063, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Layer, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btn_oficinaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_oficinaMouseEntered
     btn_oficina.setBackground(new java.awt.Color(0,95,173)); //Color azul
}//GEN-LAST:event_btn_oficinaMouseEntered

private void btn_oficinaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_oficinaMouseExited
    if(oficina==0)
    {
        btn_oficina.setBackground(new java.awt.Color(51,51,51));
    }
}//GEN-LAST:event_btn_oficinaMouseExited

private void btn_registrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_registrarMouseEntered
    btn_registrar.setBackground(new java.awt.Color(255,51,0)); //Color naranja
}//GEN-LAST:event_btn_registrarMouseEntered

private void btn_registrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_registrarMouseExited
    if(registrar==0)
    {
        btn_registrar.setBackground(new java.awt.Color(51,51,51));
    }    
}//GEN-LAST:event_btn_registrarMouseExited

private void btn_busquedaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_busquedaMouseEntered
    btn_busqueda.setBackground(new java.awt.Color(235,0,15));
}//GEN-LAST:event_btn_busquedaMouseEntered

private void btn_busquedaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_busquedaMouseExited
    if(busqueda==0)
    {
        btn_busqueda.setBackground(new java.awt.Color(51,51,51));
    }
}//GEN-LAST:event_btn_busquedaMouseExited

private void btn_informesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_informesMouseEntered
    btn_informes.setBackground(new java.awt.Color(0,95,173));
}//GEN-LAST:event_btn_informesMouseEntered

private void btn_informesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_informesMouseExited
    if(informes==0)
    {
        btn_informes.setBackground(new java.awt.Color(51,51,51));
    }
}//GEN-LAST:event_btn_informesMouseExited

private void btn_opcionesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_opcionesMouseEntered
    btn_opciones.setBackground(new java.awt.Color(255,51,0));
}//GEN-LAST:event_btn_opcionesMouseEntered

private void btn_opcionesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_opcionesMouseExited
    if(opciones==0)
    {
        btn_opciones.setBackground(new java.awt.Color(51,51,51));
    }
}//GEN-LAST:event_btn_opcionesMouseExited

private void btn_registrosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_registrosMouseEntered
    btn_registros.setBackground(new java.awt.Color(0,158,56));
}//GEN-LAST:event_btn_registrosMouseEntered

private void btn_registrosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_registrosMouseExited
    if(registros==0)
    {
        btn_registros.setBackground(new java.awt.Color(51,51,51));
    }
}//GEN-LAST:event_btn_registrosMouseExited

private void btn_salirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_salirMouseEntered
    btn_salir.setBackground(new java.awt.Color(235,0,15));
}//GEN-LAST:event_btn_salirMouseEntered

private void btn_salirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_salirMouseExited
    if(salir==0)
    {
        btn_salir.setBackground(new java.awt.Color(51,51,51));
    }
}//GEN-LAST:event_btn_salirMouseExited

private void btn_oficinaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_oficinaMouseClicked
    this.setIconImage (new ImageIcon(getClass().getResource("/Iconos/Panel.png")).getImage());
    this.setTitle("CONTROL DE OFICINA");
    Layer.removeAll();
    btn_oficina.setBackground(new java.awt.Color(0,95,173)); //Color azul
    Paneles.PanelControl Pc=new Paneles.PanelControl(Layer.getSize(), fecha, Layer);
    Layer.add(Pc,BorderLayout.CENTER);
    Layer.repaint();
    
    oficina=1;registrar=0;busqueda=0;informes=0;registros=0;opciones=0;salir=0;
    MauseExit();
}//GEN-LAST:event_btn_oficinaMouseClicked

private void btn_registrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_registrarMouseClicked
    this.setIconImage (new ImageIcon(getClass().getResource("/Iconos/address.png")).getImage());
    this.setTitle("REGISTRO");
    Layer.removeAll();
    Paneles.PanelAux Aux=new PanelAux(Layer.getSize());
    Layer.add(Aux);
    
    oficina=0;registrar=1;busqueda=0;informes=0;registros=0;opciones=0;salir=0;
    MauseExit();
}//GEN-LAST:event_btn_registrarMouseClicked

private void btn_busquedaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_busquedaMouseClicked
    this.setIconImage (new ImageIcon(getClass().getResource("/Iconos/search.png")).getImage());
    this.setTitle("CONSULTA");
    Layer.removeAll();
    oficina=0;registrar=0;busqueda=1;informes=0;registros=0;opciones=0;salir=0;
    MauseExit();
}//GEN-LAST:event_btn_busquedaMouseClicked

private void btn_informesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_informesMouseClicked
    this.setIconImage (new ImageIcon(getClass().getResource("/Iconos/chart.png")).getImage());
    this.setTitle("INFORMES");
    Layer.removeAll();
    oficina=0;registrar=0;busqueda=0;informes=1;registros=0;opciones=0;salir=0;
    MauseExit();
}//GEN-LAST:event_btn_informesMouseClicked

private void btn_registrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_registrosMouseClicked
    this.setIconImage (new ImageIcon(getClass().getResource("/Iconos/Historial.png")).getImage());
    this.setTitle("HISTORIAL");
    oficina=0;registrar=0;busqueda=0;informes=0;registros=1;opciones=0;salir=0;
    MauseExit();
}//GEN-LAST:event_btn_registrosMouseClicked

private void btn_opcionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_opcionesMouseClicked
    this.setIconImage (new ImageIcon(getClass().getResource("/Iconos/gear.png")).getImage());
    this.setTitle("OPCIONES");
    Layer.removeAll();
    oficina=0;registrar=0;busqueda=0;informes=0;registros=0;opciones=1;salir=0;
    MauseExit();
}//GEN-LAST:event_btn_opcionesMouseClicked

private void btn_salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_salirMouseClicked
    this.setIconImage (new ImageIcon(getClass().getResource("/Iconos/lock.png")).getImage());
    this.setTitle("CERRAR");
    Layer.removeAll();
    oficina=0;registrar=0;busqueda=0;informes=0;registros=0;opciones=0;salir=1;
    MauseExit();
    Menu M=new Menu();
    Dialogos.Opcion C=new Dialogos.Opcion(this, true);
    C.setTitle("Cerrar sesion");
    //C.setIconImage (new ImageIcon(getClass().getResource("/Recursos/lock.png")).getImage());
    C.show();
    
    int opcion=C.opcion();
    if(opcion==1)
    {
        M.show();
        this.dispose();
    }
    else
    {
        C.dispose();
        btn_oficinaMouseClicked(null);
        
    }
}//GEN-LAST:event_btn_salirMouseClicked


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Control.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Control.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Control.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Control.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Control().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane Layer;
    private javax.swing.JPanel btn_busqueda;
    private javax.swing.JPanel btn_informes;
    private javax.swing.JPanel btn_oficina;
    private javax.swing.JPanel btn_opciones;
    private javax.swing.JPanel btn_registrar;
    private javax.swing.JPanel btn_registros;
    private javax.swing.JPanel btn_salir;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lblFechaLarga;
    private javax.swing.JLabel lbl_busqueda;
    private javax.swing.JLabel lbl_informes;
    private javax.swing.JLabel lbl_oficina;
    private javax.swing.JLabel lbl_opciones;
    private javax.swing.JLabel lbl_registrar;
    private javax.swing.JLabel lbl_registros;
    private javax.swing.JLabel lbl_salir;
    // End of variables declaration//GEN-END:variables
}
