
package Buttons;

import java.awt.*;
import java.awt.event.*;

public class Salir extends javax.swing.JPanel implements MouseListener{

    Color Azul=(new java.awt.Color(0,95,173));
    Color Naranja=(new java.awt.Color(255,51,0));
    Color Rojo=(new java.awt.Color(255,0,15));
    Color Verde=(new java.awt.Color(0,158,56));
    Color Gris=(new java.awt.Color(51,51,51));
    Color Claro=(new java.awt.Color(204,204,204));
    Color Blanco=(new java.awt.Color(255,255,255));
    Color Negro=(new java.awt.Color(0,0,0));
    
    public Salir() {
        super();
        initComponents();
        this.setCursor(new Cursor(Cursor.HAND_CURSOR));
        this.addMouseListener(this);
    }
    
    public void mouseClicked(MouseEvent e) {        
         
     }
 
     public void mousePressed(MouseEvent e) {
         
     }
 
     public void mouseReleased(MouseEvent e) {
         
     }
 
     public void mouseEntered(MouseEvent e) {
        this.setBackground(Rojo);
        texto.setForeground(Blanco);
     }
 
     public void mouseExited(MouseEvent e) {
         this.setBackground(Claro);
         texto.setForeground(Negro);
     }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        texto = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setPreferredSize(new java.awt.Dimension(120, 40));

        texto.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        texto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        texto.setText("SALIR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
            .addComponent(texto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addComponent(texto, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel texto;
    // End of variables declaration//GEN-END:variables
}
