
package Interfaz;

import java.awt.Color;
import javax.swing.ImageIcon;

public class Integrador extends javax.swing.JFrame {

    Color Azul=(new java.awt.Color(0,95,173));
    Color Naranja=(new java.awt.Color(255,51,0));
    Color Rojo=(new java.awt.Color(255,0,15));
    Color Verde=(new java.awt.Color(0,158,56));
    Color Gris=(new java.awt.Color(51,51,51));
    Color A=(new java.awt.Color(38,38,38));
    Color B=(new java.awt.Color(204,204,204));
    
    public Integrador() {
        initComponents();
        this.setTitle("Hotel Suite San Juan - Alamos, Sonora");
        this.setIconImage (new ImageIcon(getClass().getResource("/Iconos/hotel.png")).getImage());
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(B);
    }
    
    public void Exited(int a, int b, int c, int d, int e, int f, int g){
        control.status(a);
        registro.status(b);
        consulta.status(c);
        informes.status(d);
        historial.status(e);
        opciones.status(f);
        cerrar.status(g);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        control = new Buttons.Control();
        registro = new Buttons.Registro();
        consulta = new Buttons.Consulta();
        informes = new Buttons.Informes();
        historial = new Buttons.Historial();
        opciones = new Buttons.Opciones();
        cerrar = new Buttons.Cerrar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(38, 38, 38));

        control.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(38, 38, 38)));
        control.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                controlMouseClicked(evt);
            }
        });
        control.setBounds(30, 0, 100, 120);
        jLayeredPane1.add(control, javax.swing.JLayeredPane.DEFAULT_LAYER);

        registro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(38, 38, 38)));
        registro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registroMouseClicked(evt);
            }
        });
        registro.setBounds(130, 0, 100, 120);
        jLayeredPane1.add(registro, javax.swing.JLayeredPane.DEFAULT_LAYER);

        consulta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(38, 38, 38)));
        consulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                consultaMouseClicked(evt);
            }
        });
        consulta.setBounds(230, 0, 100, 120);
        jLayeredPane1.add(consulta, javax.swing.JLayeredPane.DEFAULT_LAYER);

        informes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(38, 38, 38)));
        informes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                informesMouseClicked(evt);
            }
        });
        informes.setBounds(330, 0, 100, 120);
        jLayeredPane1.add(informes, javax.swing.JLayeredPane.DEFAULT_LAYER);

        historial.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(38, 38, 38)));
        historial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                historialMouseClicked(evt);
            }
        });
        historial.setBounds(430, 0, 100, 120);
        jLayeredPane1.add(historial, javax.swing.JLayeredPane.DEFAULT_LAYER);

        opciones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(38, 38, 38)));
        opciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                opcionesMouseClicked(evt);
            }
        });
        opciones.setBounds(530, 0, 100, 120);
        jLayeredPane1.add(opciones, javax.swing.JLayeredPane.DEFAULT_LAYER);

        cerrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(38, 38, 38)));
        cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarMouseClicked(evt);
            }
        });
        cerrar.setBounds(630, 0, 100, 120);
        jLayeredPane1.add(cerrar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 755, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(124, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(634, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void controlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_controlMouseClicked
    control.mouseEntered(null);
    Exited(1, 0, 0, 0, 0, 0, 0);  
}//GEN-LAST:event_controlMouseClicked

private void registroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registroMouseClicked
    Exited(0, 1, 0, 0, 0, 0, 0);
}//GEN-LAST:event_registroMouseClicked

private void consultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultaMouseClicked
    Exited(0, 0, 1, 0, 0, 0, 0);
}//GEN-LAST:event_consultaMouseClicked

private void informesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_informesMouseClicked
    Exited(0, 0, 0, 1, 0, 0, 0);
}//GEN-LAST:event_informesMouseClicked

private void historialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_historialMouseClicked
    Exited(0, 0, 0, 0, 1, 0, 0);
}//GEN-LAST:event_historialMouseClicked

private void opcionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opcionesMouseClicked
    Exited(0, 0, 0, 0, 0, 1, 0);
}//GEN-LAST:event_opcionesMouseClicked

private void cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseClicked
    Exited(0, 0, 0, 0, 0, 0, 1);
}//GEN-LAST:event_cerrarMouseClicked


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Integrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Integrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Integrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Integrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Integrador().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Buttons.Cerrar cerrar;
    private Buttons.Consulta consulta;
    private Buttons.Control control;
    private Buttons.Historial historial;
    private Buttons.Informes informes;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private Buttons.Opciones opciones;
    private Buttons.Registro registro;
    // End of variables declaration//GEN-END:variables
}
